common:
  version: '0.1'
  server:
    host: '0.0.0.0'
    port: 5000
  log:
    conf: 'logging_dev.yaml'
  aws:
    url: 'https://{}.s3-ap-northeast-1.amazonaws.com/{}'
  mm_division:
    file_path: '/../../data/mm_division/division.json'
  default_address:
    division: "ayeyarwady"
    district: "maubin"
    township: "nyaungdone"
    street_address: "တိုက်သစ်ကျောင်း"
postgres:
  url: 'postgresql://'
  host: 'db'
  port: 5432
  user: 'thingaha'
  password: 'thingaha'
  db: 'thingaha_dev'
