common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5555
    log:
        conf: "logging_staging.yaml"
    mm_division:
        file_path: "/../../data/mm_division/division.json"
    default_address:
        division: "ayeyarwady"
        district: "maubin"
        township: "nyaungdone"
        street_address: "တိုက်သစ်ကျောင်း"
