common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5555
    log:
        conf: "logging_prod.yaml"
    aws:
        url: "https://{}.s3-ap-northeast-1.amazonaws.com/{}"
    mm_division:
        file_path: "/../../data/mm_division/division.json"
    default_address:
        division: "ayeyarwady"
        district: "maubin"
        township: "nyaungdone"
        street_address: "တိုက်သစ်ကျောင်း"
postgres:
    url: "postgresql://"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "XXXXXX"
    db: "thingaha"
