FROM ubuntu:20.04

COPY ./backend /app
WORKDIR /app
RUN apt-get update -y && apt-get install -y python3-pip libsasl2-dev python3-dev libldap2-dev libssl-dev libsnmp-dev libpq-dev
RUN pip3 install --no-cache-dir -r requirements.txt
ENV FLASK_ENV production
ENV SCRIPT_ENV production
ENV FLASK_APP app.py

WORKDIR /app/bin

ENTRYPOINT ["/bin/sh", "./docker_entry_point.sh"]

EXPOSE 5000
