"""empty message

Revision ID: 03b7c2966296
Revises: 0f053e41a8d9
Create Date: 2020-11-04 22:49:40.554885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b7c2966296'
down_revision = '0f053e41a8d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('extrafunds_transfer_id_fkey', 'extrafunds', type_='foreignkey')
    op.drop_column('extrafunds', 'transfer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extrafunds', sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('extrafunds_transfer_id_fkey', 'extrafunds', 'transfers', ['transfer_id'], ['id'])
    # ### end Alembic commands ###
