"""empty message

Revision ID: 0c91da7fa8bf
Revises: 80855b0b50f0
Create Date: 2020-07-22 22:47:23.231708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c91da7fa8bf'
down_revision = '80855b0b50f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'paid_at')
    # ### end Alembic commands ###
