"""empty message

Revision ID: 1c09172a8632
Revises: a761f251acf0
Create Date: 2020-12-13 15:30:31.237092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c09172a8632'
down_revision = 'a761f251acf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'division',
               existing_type=postgresql.ENUM('yangon', 'ayeyarwady', 'chin', 'kachin', 'kayah', 'kayin', 'mon', 'rakhine', 'shan', 'bago', 'magway', 'mandalay', 'sagaing', 'tanintharyi', name='division'),
               type_=sa.UnicodeText(),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=postgresql.ENUM('jp', 'mm', 'sg', 'th', name='country'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'country',
               existing_type=sa.String(),
               type_=postgresql.ENUM('jp', 'mm', 'sg', 'th', name='country'),
               existing_nullable=True)
    op.alter_column('addresses', 'division',
               existing_type=sa.UnicodeText(),
               type_=postgresql.ENUM('yangon', 'ayeyarwady', 'chin', 'kachin', 'kayah', 'kayin', 'mon', 'rakhine', 'shan', 'bago', 'magway', 'mandalay', 'sagaing', 'tanintharyi', name='division'),
               existing_nullable=True)
    # ### end Alembic commands ###
