"""empty message

Revision ID: 251014973584
Revises: 
Create Date: 2020-07-18 22:31:02.806187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251014973584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.Enum('yangon', 'ayeyarwady', 'chin', 'kachin', 'kayah', 'kayin', 'mon', 'rakhine', 'shan', 'bago', 'magway', 'mandalay', 'sagaing', 'tanintharyi', name='division_name'), nullable=True),
    sa.Column('district', sa.UnicodeText(), nullable=True),
    sa.Column('township', sa.UnicodeText(), nullable=True),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address', sa.UnicodeText(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('sub_admin', 'donator', 'admin', name='user_role'), nullable=True),
    sa.Column('country', sa.Enum('jp', 'mm', 'sg', 'th', name='country_code'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('father_name', sa.UnicodeText(), nullable=True),
    sa.Column('mother_name', sa.UnicodeText(), nullable=True),
    sa.Column('parents_occupation', sa.Text(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('users')
    op.drop_table('addresses')
    # ### end Alembic commands ###
