"""empty message

Revision ID: 56e566477302
Revises: a3d96e953f8c
Create Date: 2020-10-03 23:33:57.284121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e566477302'
down_revision = 'a3d96e953f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('year', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
