"""empty message

Revision ID: 581eacfd7ff0
Revises: 91ceaac79eae
Create Date: 2020-10-05 23:08:31.051347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '581eacfd7ff0'
down_revision = '91ceaac79eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    addresses_types = postgresql.ENUM('user', 'student', 'school', name='addresses_types')
    addresses_types.create(op.get_bind())
    op.add_column('addresses', sa.Column('type', sa.Enum('user', 'student', 'school', name='addresses_types'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'type')
    # ### end Alembic commands ###
