"""empty message

Revision ID: 76e7e368d4c2
Revises: 8307d07335d1
Create Date: 2021-07-04 13:04:53.686280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76e7e368d4c2'
down_revision = '8307d07335d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    gender = postgresql.ENUM('Female', 'Male', 'Non-Binary', name='gender')
    gender.create(op.get_bind())
    op.add_column('students', sa.Column('gender', sa.Enum('Female', 'Male', 'Non-Binary', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gender')
    banner_status = postgresql.ENUM('Female', 'Male', 'Non-Binary', name='gender')
    banner_status.drop(op.get_bind())
    # ### end Alembic commands ###
