"""empty message

Revision ID: 8307d07335d1
Revises: 728c4dfae81d
Create Date: 2021-06-13 22:39:12.308545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8307d07335d1'
down_revision = '728c4dfae81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('photo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'photo')
    # ### end Alembic commands ###
