"""empty message

Revision ID: 91ceaac79eae
Revises: 56e566477302
Create Date: 2020-10-03 23:34:05.120034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ceaac79eae'
down_revision = '56e566477302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_column('attendances', 'year1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('year1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('attendances', 'year')
    # ### end Alembic commands ###
