"""empty message

Revision ID: a3d96e953f8c
Revises: da8866375bf2
Create Date: 2020-10-03 23:33:43.034004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d96e953f8c'
down_revision = 'da8866375bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('year1', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'year1')
    # ### end Alembic commands ###
