"""empty message

Revision ID: a6a097726e6f
Revises: 1e9c73166fb0
Create Date: 2021-05-08 11:32:52.503454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a097726e6f'
down_revision = '1e9c73166fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.UnicodeText(), nullable=True),
    sa.Column('district', sa.UnicodeText(), nullable=True),
    sa.Column('township', sa.UnicodeText(), nullable=True),
    sa.Column('street_address', sa.UnicodeText(), nullable=True),
    sa.Column('type', sa.Enum('user', 'student', 'school', name='addresses_types'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', name='transfer_month'), nullable=True),
    sa.Column('total_mmk', sa.Float(), nullable=True),
    sa.Column('total_jpy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extrafunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmk_amount', sa.Float(), nullable=True),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('father_name', sa.UnicodeText(), nullable=True),
    sa.Column('mother_name', sa.UnicodeText(), nullable=True),
    sa.Column('parents_occupation', sa.Text(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('sub_admin', 'donator', 'admin', name='role'), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('donation_active', sa.Boolean(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Enum('KG', 'G-1', 'G-2', 'G-3', 'G-4', 'G-5', 'G-6', 'G-7', 'G-8', 'G-9', 'G-10', 'G-11', 'G-12', name='grade'), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('enrolled_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december', name='month'), nullable=True),
    sa.Column('mmk_amount', sa.Float(), nullable=True),
    sa.Column('jpy_amount', sa.Float(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('attendances')
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('extrafunds')
    op.drop_table('transfers')
    op.drop_table('addresses')
    # ### end Alembic commands ###
