"""empty message

Revision ID: a761f251acf0
Revises: 03b7c2966296
Create Date: 2020-11-04 22:49:52.078252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a761f251acf0'
down_revision = '03b7c2966296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extrafunds', sa.Column('transfer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'extrafunds', 'transfers', ['transfer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extrafunds', type_='foreignkey')
    op.drop_column('extrafunds', 'transfer_id')
    # ### end Alembic commands ###
