"""empty message

Revision ID: da8866375bf2
Revises: 79b598104aae
Create Date: 2020-10-03 23:17:27.121743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8866375bf2'
down_revision = '79b598104aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donations', 'transfer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('donation_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'donation_active')
    op.alter_column('donations', 'transfer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
